#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fit_ns_tool
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties.hibarnate.dailect: org.hibernate.dialect.MySQL5Dialect